repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks: [{ id: ruff }, { id: ruff-format }]
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks: [{ id: black }]
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks: [{ id: isort }]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks: [{ id: prettier }]
