name: CI

on:
  push:
    branches: [main, chore/**, fix/**, feat/**]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend (pre-commit + pytest)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install pre-commit
          pip install -e .[dev] || pip install -e .
          pip install pytest httpx fastapi "uvicorn[standard]" bcrypt python-multipart

      - name: Run pre-commit (ruff, black, isort, prettier)
        run: pre-commit run --all-files

      - name: Run backend tests
        run: pytest -q

  frontend:
    name: Frontend (lint + test + build)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps (clean)
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test (Vitest)
        run: npm run test -- --run

      - name: Build
        run: npm run build
