name: CI

on:
  push:
    branches: [main, chore/**, fix/**, feat/**]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend (pre-commit + pytest)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install pre-commit
          pip install -e .[dev] || pip install -e .
          pip install pytest httpx fastapi "uvicorn[standard]"

      - name: Run pre-commit (ruff, black, isort, prettier)
        run: pre-commit run --all-files

      - name: Run backend tests
        run: pytest -q
